//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thithu1.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Sanpham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sanpham()
        {
            this.ChiTietDonHangs = new HashSet<ChiTietDonHang>();
            this.MauSacs = new HashSet<MauSac>();
        }


        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int SanphamID { get; set; }

        [DisplayName("Ten san pham")]
        [Required(ErrorMessage ="Ten san pham bat buoc phai nhap")]
        public string TenSanpham { get; set; }
        [DisplayName("Mo ta san pham")]
        [Required(ErrorMessage = "Mo ta san pham bat buoc phai nhap")]

        public string MoTa { get; set; }
        [DisplayName("Don gia san pham (USD)")]
        [Required(ErrorMessage = "Don gia san pham bat buoc phai nhap")]
        [RegularExpression(@"^\d+(\.\d{1,2})?$", ErrorMessage = "Don gia san pham phai la so hop le")]
        public decimal Gia { get; set; }
        [DisplayName("Trang thai san pham")]
        [Required(ErrorMessage = "Trang thai san pham bat buoc phai nhap")]

        public Nullable<byte> TrangThai { get; set; }
        [DisplayName("Anh san pham")]

        public string AnhDaiDien { get; set; }
        [DisplayName("La san pham noi bat")]

        public Nullable<byte> NoiBat { get; set; }
        [DisplayName("Danh muc san pham")]
        [Required(ErrorMessage = "Danh muc san pham bat buoc phai nhap")]

        public Nullable<int> PhanLoaiSanPhamID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }
        public virtual PhanLoaiSanPham PhanLoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MauSac> MauSacs { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
